# Generated by Django 3.2 on 2021-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.IntegerField()),
                ('cat1', models.CharField(max_length=100)),
                ('cat2', models.CharField(max_length=100)),
                ('content_id', models.IntegerField()),
                ('content_type', models.IntegerField()),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('readcount', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour_spot_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('content_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('content_type', models.IntegerField()),
            ],
        ),
    ]
