# Generated by Django 3.2 on 2021-04-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_spot',
            old_name='areareacode',
            new_name='areacode',
        ),
    ]
