# Generated by Django 3.2 on 2021-04-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_tour_spot_rating_areacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_spot_rating',
            name='areacode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour_spot_rating',
            name='content_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour_spot_rating',
            name='content_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour_spot_rating',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
