# Generated by Django 3.1.5 on 2021-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210425_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('34', '충청남도'), ('39', '제주도'), ('5', '광주'), ('8', '세종특별자치시'), ('35', '경상북도'), ('32', '강원도'), ('7', '울산'), ('33', '충청북도'), ('36', '경상남도'), ('3', '대전'), ('2', '인천'), ('1', '서울'), ('37', '전라북도'), ('38', '전라남도'), ('6', '부산'), ('31', '경기도'), ('4', '대구')], default='1', max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('S02', '여자'), ('S01', '남자')], default='S01', max_length=10, verbose_name='성별'),
        ),
    ]
