# Generated by Django 3.1.5 on 2021-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210426_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('5', '광주'), ('7', '울산'), ('8', '세종특별자치시'), ('34', '충청남도'), ('31', '경기도'), ('6', '부산'), ('37', '전라북도'), ('39', '제주도'), ('33', '충청북도'), ('32', '강원도'), ('1', '서울'), ('2', '인천'), ('35', '경상북도'), ('36', '경상남도'), ('4', '대구'), ('38', '전라남도'), ('3', '대전')], default='1', max_length=10, verbose_name='주소'),
        ),
    ]
