# Generated by Django 3.1.5 on 2021-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210426_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('2', '인천'), ('37', '전라북도'), ('31', '경기도'), ('35', '경상북도'), ('7', '울산'), ('1', '서울'), ('6', '부산'), ('3', '대전'), ('4', '대구'), ('39', '제주도'), ('38', '전라남도'), ('33', '충청북도'), ('36', '경상남도'), ('34', '충청남도'), ('8', '세종특별자치시'), ('5', '광주'), ('32', '강원도')], default='1', max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('S01', '남자'), ('S02', '여자')], default='S01', max_length=10, verbose_name='성별'),
        ),
    ]
