# Generated by Django 3.1.5 on 2021-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210426_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('3', '대전'), ('31', '경기도'), ('38', '전라남도'), ('33', '충청북도'), ('35', '경상북도'), ('7', '울산'), ('37', '전라북도'), ('1', '서울'), ('34', '충청남도'), ('8', '세종특별자치시'), ('32', '강원도'), ('36', '경상남도'), ('4', '대구'), ('6', '부산'), ('5', '광주'), ('2', '인천'), ('39', '제주도')], default='1', max_length=10, verbose_name='주소'),
        ),
    ]
