# Generated by Django 3.1.5 on 2021-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210426_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('1', '서울'), ('35', '경상북도'), ('4', '대구'), ('3', '대전'), ('33', '충청북도'), ('6', '부산'), ('8', '세종특별자치시'), ('36', '경상남도'), ('37', '전라북도'), ('39', '제주도'), ('31', '경기도'), ('38', '전라남도'), ('32', '강원도'), ('2', '인천'), ('34', '충청남도'), ('5', '광주'), ('7', '울산')], default='1', max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('S02', '여자'), ('S01', '남자')], default='S01', max_length=10, verbose_name='성별'),
        ),
    ]
