# Generated by Django 3.1.5 on 2021-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210426_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('5', '광주'), ('38', '전라남도'), ('33', '충청북도'), ('31', '경기도'), ('39', '제주도'), ('6', '부산'), ('35', '경상북도'), ('34', '충청남도'), ('37', '전라북도'), ('1', '서울'), ('32', '강원도'), ('36', '경상남도'), ('4', '대구'), ('2', '인천'), ('8', '세종특별자치시'), ('7', '울산'), ('3', '대전')], default='1', max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('S01', '남자'), ('S02', '여자')], default='S01', max_length=10, verbose_name='성별'),
        ),
    ]
