# Generated by Django 3.1.5 on 2021-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210426_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('5', '광주'), ('6', '부산'), ('38', '전라남도'), ('36', '경상남도'), ('35', '경상북도'), ('32', '강원도'), ('8', '세종특별자치시'), ('39', '제주도'), ('4', '대구'), ('33', '충청북도'), ('7', '울산'), ('37', '전라북도'), ('34', '충청남도'), ('1', '서울'), ('3', '대전'), ('2', '인천'), ('31', '경기도')], default='1', max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('S02', '여자'), ('S01', '남자')], default='S01', max_length=10, verbose_name='성별'),
        ),
    ]
