# Generated by Django 3.1.5 on 2021-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.CharField(max_length=20, unique=True)),
                ('cat1', models.CharField(max_length=20)),
                ('cat2', models.CharField(max_length=20)),
                ('contenttypeid', models.CharField(max_length=20, unique=True)),
                ('mapx', models.CharField(max_length=20)),
                ('tour_Tablecol', models.CharField(max_length=20)),
                ('readcount', models.IntegerField()),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFakeDataTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('contentcode', models.CharField(max_length=20)),
                ('contentdes', models.CharField(max_length=20)),
                ('click', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRatingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('contentid', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('contenttypeid', models.CharField(max_length=20)),
                ('areacode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserThemaDataTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('themaCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyTripData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('contentcode', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('userId', 'contentcode')},
            },
        ),
        migrations.CreateModel(
            name='CodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=20)),
                ('code_info', models.CharField(max_length=20)),
                ('code_from', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('code_id', 'code_info')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenttypeid', models.CharField(max_length=20)),
                ('cat1', models.CharField(max_length=20)),
                ('cat1_name', models.CharField(max_length=20)),
                ('cat2', models.CharField(max_length=20)),
                ('cat2_name', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('contenttypeid', 'cat1', 'cat2')},
            },
        ),
    ]
