# Generated by Django 3.1.5 on 2021-04-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codedata',
            unique_together=set(),
        ),
    ]
