# Generated by Django 3.1.5 on 2021-04-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210426_0011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classificationcode',
            unique_together=set(),
        ),
    ]
