# Generated by Django 3.1.5 on 2021-04-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210426_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.CharField(max_length=20, unique=True)),
                ('contenttypeid', models.CharField(max_length=20, unique=True)),
                ('mapx', models.CharField(max_length=20)),
                ('mapy', models.CharField(max_length=20)),
                ('tour_Tablecol', models.CharField(max_length=20)),
                ('readcount', models.IntegerField()),
                ('title', models.CharField(max_length=20, unique=True)),
                ('class_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classificationcode')),
            ],
        ),
        migrations.DeleteModel(
            name='DestinationDataset',
        ),
    ]
