# Generated by Django 3.1.5 on 2021-04-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210426_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationData',
        ),
    ]
