# Generated by Django 3.1.5 on 2021-04-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_destinationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationCode',
        ),
        migrations.DeleteModel(
            name='CodeData',
        ),
        migrations.DeleteModel(
            name='MyTripData',
        ),
        migrations.DeleteModel(
            name='UserFakeDataTwo',
        ),
        migrations.DeleteModel(
            name='UserRatingData',
        ),
    ]
