# Generated by Django 3.1.5 on 2021-04-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210426_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogData',
        ),
        migrations.DeleteModel(
            name='UserThemaDataTwo',
        ),
    ]
