# Generated by Django 3.1.5 on 2021-04-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTripData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TravelSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.IntegerField()),
                ('cat1', models.CharField(max_length=100)),
                ('cat2', models.CharField(max_length=100)),
                ('content_id', models.IntegerField()),
                ('content_type', models.IntegerField()),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('readcount', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('mytripdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.mytripdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mytripdata',
            name='travelspot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travelspot'),
        ),
        migrations.AddField(
            model_name='mytripdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
