# Generated by Django 3.1.5 on 2021-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenttypeid', models.CharField(max_length=20)),
                ('cat1', models.CharField(max_length=20)),
                ('cat1_name', models.CharField(max_length=20)),
                ('cat2', models.CharField(max_length=20)),
                ('cat2_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=20)),
                ('code_info', models.CharField(max_length=20)),
                ('code_from', models.CharField(max_length=20)),
            ],
        ),
    ]
