# Generated by Django 3.1.5 on 2021-04-25 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0002_classificationcode_codedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('travelspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travelspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
